# main menu navigation
menu:
  Index: /
  Tags: /tags
  Archives: /archives

# index page dream text,
dream:
  enable: true
  text: 要靠体验新事物来保持活力 （The core of mans' spirit comes from new experiences）
# show post-calendar
postCalendar: true

# Miscelaneous
favicon: /favicon.png
logo: /medias/logo.png

# the gitment config，default disabled
gitment:
  enable: true
  owner: smalbox
  repo: smalbox.github.io
  oauth: 
    clientId: a0909d072a0882970281
    clientSecret: e201a3feaa60ff9087217ad3bcefeeb358acc540

# disqus config, default disabled
disqus:
  enable: false
  shortname:

# posts feature images
featureImages: 
- /medias/featureimages/0.jpg
- /medias/featureimages/1.jpg
- /medias/featureimages/2.jpg
- /medias/featureimages/3.jpg
- /medias/featureimages/4.jpg
- /medias/featureimages/5.jpg
- /medias/featureimages/6.jpg
- /medias/featureimages/7.jpg
- /medias/featureimages/8.jpg
- /medias/featureimages/9.jpg
- /medias/featureimages/10.jpg
- /medias/featureimages/11.jpg
- /medias/featureimages/12.jpg
- /medias/featureimages/13.jpg
- /medias/featureimages/14.jpg
- /medias/featureimages/15.jpg
- /medias/featureimages/16.jpg
- /medias/featureimages/17.jpg
- /medias/featureimages/18.jpg
- /medias/featureimages/19.jpg
- /medias/featureimages/20.jpg
- /medias/featureimages/21.jpg
- /medias/featureimages/22.jpg
- /medias/featureimages/23.jpg
